name: Deploy Flutter App

on:
  push:
    # Triggers only on pushes to main
    branches:
      - main
    # Also triggers when you push tags (so you can use an explicit version tag)
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android release APK
        run: flutter build apk --release

      # Create or update a GitHub Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          # If you pushed a tag like v1.2.3, use that; otherwise derive a tag
          tag_name: ${{ github.ref_name != 'main' && startsWith(github.ref, 'refs/tags/') && github.ref_name || format('v0.0.{0}', github.run_number) }}
          release_name: Release ${{ steps.create_release.outputs.tag_name }}
          draft: false
          prerelease: false

      # Upload the built APK to the Release
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
